import styled from 'styled-components';
import SearchLogo from '../assets/images/search.svg';
import SelectLogo from '../assets/images/select.svg';
import StandoutLogo from '../assets/images/standout.svg';

const Wrapper = styled.div`
    height: 13.75em;
    padding: 3.75em 11.5em 3em;
    width: calc(100% - 23em);
    background-color: rgba(20, 110, 180, 0.1);
    display: flex;
    align-items: center;
    justify-content: space-between;
`
const ElementWrapper = styled.div`
    width: 31%;
    height: 100%;
    text-align: center;
`
const ElementImage = styled.img`
    height: 4.5em;
`
const ElementLabel = styled.div`
    margin: 1em 0 0.5em;
    font-size: 1.25em;
    color: #1A181E;
    font-family: Galano-Medium;
`
const ElementDesc = styled.div`
    color: #4D4D4D;
    font-family: Galano-Regular;
    font-size: 1em;
    line-height: 1.5;
    text-align: center;
`
export default function Details(){
    return(
        <Wrapper>
            <ElementWrapper>
                <ElementImage src={SearchLogo} alt="search"/>
                <ElementLabel>Search</ElementLabel>
                <ElementDesc>Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.</ElementDesc>
            </ElementWrapper>
            <ElementWrapper>
                <ElementImage src={SelectLogo} alt="select"/>
                <ElementLabel>Select</ElementLabel>
                <ElementDesc>Choose from thousands of options generated by the slogan maker that fit your needs.</ElementDesc>
            </ElementWrapper>
            <ElementWrapper>
                <ElementImage src={StandoutLogo} alt="standout"/>
                <ElementLabel>Standout</ElementLabel>
                <ElementDesc>Congrats on your new slogan. It's time to win the world!</ElementDesc>
            </ElementWrapper>
        </Wrapper>
    )
}